const mongoose = require('mongoose');

const alertSchema = new mongoose.Schema({
  type: {
    type: String,
    enum: ['tutor', 'student', 'payment', 'system'],
    required: true,
  },
  priority: {
    type: String,
    enum: ['high', 'medium', 'low'],
    default: 'medium',
  },
  title: { type: String, required: true },
  description: { type: String, required: true },
  refModel: { type: String, enum: ['Tutor', 'Student', 'Payment', null], default: null },
  refId: { type: mongoose.Schema.Types.ObjectId, default: null },
  status: {
    type: String,
    enum: ['unresolved', 'resolved', 'dismissed'],
    default: 'unresolved',
  },
  resolvedAt: Date,
  resolvedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  autoGenerated: { type: Boolean, default: true },
  actions: [{ label: String, action: String, style: String }],
}, { timestamps: true });

module.exports = mongoose.model('Alert', alertSchema);
