const express = require('express');
const Alert = require('../models/Alert');
const Tutor = require('../models/Tutor');
const User = require('../models/User');
const { protect, authorize } = require('../middleware/auth');

const router = express.Router();

// GET all
router.get('/', protect, async (req, res) => {
  try {
    const { type, priority, status = 'unresolved', page = 1, limit = 30 } = req.query;
    const query = { status };
    if (type && type !== 'all') query.type = type;
    if (priority) query.priority = priority;

    const [alerts, total, unresolvedCount] = await Promise.all([
      Alert.find(query).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(Number(limit)).lean(),
      Alert.countDocuments(query),
      Alert.countDocuments({ status: 'unresolved' }),
    ]);

    const order = { high: 0, medium: 1, low: 2 };
    alerts.sort((a, b) => order[a.priority] - order[b.priority]);

    res.json({ success: true, data: alerts, total, unresolvedCount, page: Number(page), pages: Math.ceil(total / limit) });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// GET one
router.get('/:id', protect, async (req, res) => {
  try {
    const alert = await Alert.findById(req.params.id);
    if (!alert) return res.status(404).json({ success: false, message: 'Alert not found' });
    res.json({ success: true, data: alert });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// POST create (manual alert)
router.post('/', protect, authorize('super_admin', 'operations'), async (req, res) => {
  try {
    const alert = await Alert.create({ ...req.body, autoGenerated: false });
    res.status(201).json({ success: true, data: alert });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
});

// PUT update
router.put('/:id', protect, authorize('super_admin', 'operations'), async (req, res) => {
  try {
    const alert = await Alert.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true });
    if (!alert) return res.status(404).json({ success: false, message: 'Alert not found' });
    res.json({ success: true, data: alert });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
});

// DELETE
router.delete('/:id', protect, authorize('super_admin'), async (req, res) => {
  try {
    const alert = await Alert.findByIdAndDelete(req.params.id);
    if (!alert) return res.status(404).json({ success: false, message: 'Alert not found' });
    res.json({ success: true, message: 'Alert deleted' });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// PATCH resolve
router.patch('/:id/resolve', protect, async (req, res) => {
  try {
    const alert = await Alert.findByIdAndUpdate(
      req.params.id,
      { status: 'resolved', resolvedAt: new Date(), resolvedBy: req.user._id },
      { new: true }
    );
    if (!alert) return res.status(404).json({ success: false, message: 'Alert not found' });
    res.json({ success: true, data: alert });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// PATCH dismiss
router.patch('/:id/dismiss', protect, async (req, res) => {
  try {
    const alert = await Alert.findByIdAndUpdate(req.params.id, { status: 'dismissed' }, { new: true });
    if (!alert) return res.status(404).json({ success: false, message: 'Alert not found' });
    res.json({ success: true, data: alert });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// POST approve tutor — activates Tutor + linked User, resolves alert
router.post('/:id/approve-tutor', protect, authorize('super_admin', 'support_agent'), async (req, res) => {
  try {
    const alert = await Alert.findById(req.params.id);
    if (!alert) return res.status(404).json({ success: false, message: 'Alert not found' });
    if (!alert.refId) return res.status(400).json({ success: false, message: 'Alert has no refId' });

    // 1. Activate the Tutor record
    const tutor = await Tutor.findByIdAndUpdate(
      alert.refId,
      { status: 'active' },
      { new: true },
    );
    if (!tutor) return res.status(404).json({ success: false, message: 'Tutor not found' });

    // 2. Activate the linked User account (matched by linkedId or email)
    await User.findOneAndUpdate(
      { $or: [{ linkedId: alert.refId }, { email: tutor.email }] },
      { isActive: true },
    );

    // 3. Resolve the alert
    await Alert.findByIdAndUpdate(req.params.id, {
      status: 'resolved',
      resolvedAt: new Date(),
      resolvedBy: req.user._id,
    });

    res.json({ success: true, message: `Tutor ${tutor.name} approved successfully`, tutor });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// POST feature tutor
router.post('/:id/feature-tutor', protect, authorize('super_admin', 'operations'), async (req, res) => {
  try {
    const alert = await Alert.findByIdAndUpdate(
      req.params.id,
      { status: 'resolved', resolvedAt: new Date() },
      { new: true }
    );
    if (!alert) return res.status(404).json({ success: false, message: 'Alert not found' });
    res.json({ success: true, message: 'Tutor featured successfully' });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

module.exports = router;
