const express = require('express');
const jwt = require('jsonwebtoken');
const User = require('../models/User');
const Student = require('../models/Student');
const Tutor = require('../models/Tutor');
const Alert = require('../models/Alert');
const { protect } = require('../middleware/auth');

const router = express.Router();

const signToken = (id) =>
  jwt.sign({ id }, process.env.JWT_SECRET, { expiresIn: process.env.JWT_EXPIRES_IN });

router.post('/signup', async (req, res) => {
  const {
    firstName, lastName, displayName, dob, gender,
    role = 'support_agent', email, password, phone, dialCode, countryCode,
    profileImage,
  } = req.body;
  if (!firstName || !email || !password) {
    return res.status(400).json({ success: false, message: 'firstName, email and password are required' });
  }
  try {
    const exists = await User.findOne({ email });
    if (exists) return res.status(409).json({ success: false, message: 'Email already registered' });

    const fullName = [firstName, lastName].filter(Boolean).join(' ');
    const resolvedRole = role === 'admin' ? 'support_agent' : role;
    const isActive = resolvedRole !== 'tutor'; // tutors start inactive until approved

    let linkedId = null;

    if (resolvedRole === 'student') {
      const student = await Student.create({
        name: fullName, email, phone: phone || undefined,
        profileImage: profileImage || undefined,
      });
      linkedId = student._id;
    }

    if (resolvedRole === 'tutor') {
      const tutor = await Tutor.create({
        name: fullName,
        email,
        phone: phone ? `${dialCode || ''}${phone}` : undefined,
        profileImage: profileImage || undefined,
        status: 'pending_approval',
      });
      linkedId = tutor._id;

      // Notify admins via alert
      await Alert.create({
        type: 'tutor',
        priority: 'medium',
        title: `New tutor registration: ${fullName}`,
        description: `${fullName} (${email}) signed up as a tutor and is awaiting approval.`,
        refModel: 'Tutor',
        refId: linkedId,
        status: 'unresolved',
        autoGenerated: true,
        actions: [{ label: 'Approve', action: 'approve_tutor', style: 'success' }],
      });
    }

    const user = await User.create({
      firstName,
      lastName: lastName || '',
      displayName: displayName || fullName,
      dob: dob || undefined,
      gender: gender || undefined,
      email,
      password,
      phone,
      dialCode,
      countryCode,
      profileImage: profileImage || undefined,
      role: resolvedRole,
      isActive,
      linkedId,
    });

    if (!isActive) {
      // Tutor: don't issue a token — they must wait for approval
      return res.status(201).json({ success: true, pending: true, message: 'Registration submitted. Awaiting admin approval.' });
    }

    const token = signToken(user._id);
    res.status(201).json({ success: true, token, user: user.toJSON() });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
});

// In-memory OTP store: key = `dialCode:phone`, value = { otp, expiresAt }
const otpStore = new Map();
const DEFAULT_OTP = '123456';

router.post('/send-otp', async (req, res) => {
  const { phone, dialCode } = req.body;
  if (!phone || !dialCode) {
    return res.status(400).json({ success: false, message: 'phone and dialCode are required' });
  }
  try {
    const user = await User.findOne({ phone, dialCode });
    if (!user) return res.status(404).json({ success: false, message: 'Mobile number not registered' });
    if (!user.isActive) return res.status(403).json({ success: false, message: 'Account inactive' });

    // Store OTP with 10-minute expiry (default 123456 for dev)
    const key = `${dialCode}:${phone}`;
    otpStore.set(key, { otp: DEFAULT_OTP, expiresAt: Date.now() + 10 * 60 * 1000 });

    // TODO: send real SMS in production
    res.json({ success: true, message: 'OTP sent successfully' });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

router.post('/login', async (req, res) => {
  const { email, phone, dialCode, password, otp } = req.body;
  if (!email && !phone) {
    return res.status(400).json({ success: false, message: 'Email or phone is required' });
  }
  try {
    if (phone) {
      // OTP-based mobile login
      if (!otp) return res.status(400).json({ success: false, message: 'OTP is required' });
      const key = `${dialCode}:${phone}`;
      const record = otpStore.get(key);
      if (!record) return res.status(401).json({ success: false, message: 'OTP not sent or expired. Request a new one.' });
      if (Date.now() > record.expiresAt) {
        otpStore.delete(key);
        return res.status(401).json({ success: false, message: 'OTP expired. Request a new one.' });
      }
      if (record.otp !== otp) return res.status(401).json({ success: false, message: 'Invalid OTP' });
      otpStore.delete(key);

      const user = await User.findOne({ phone, dialCode });
      if (!user || !user.isActive) return res.status(401).json({ success: false, message: 'Invalid credentials' });
      user.lastLogin = new Date();
      await user.save({ validateBeforeSave: false });
      return res.json({ success: true, token: signToken(user._id), user: user.toJSON() });
    }

    // Email + password login
    if (!password) return res.status(400).json({ success: false, message: 'Password is required' });
    const user = await User.findOne({ email }).select('+password');
    if (!user || !(await user.comparePassword(password))) {
      return res.status(401).json({ success: false, message: 'Invalid credentials' });
    }
    if (!user.isActive) return res.status(403).json({ success: false, message: 'Account inactive' });
    user.lastLogin = new Date();
    await user.save({ validateBeforeSave: false });
    res.json({ success: true, token: signToken(user._id), user: user.toJSON() });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

router.get('/me', protect, (req, res) => {
  res.json({ success: true, user: req.user });
});

// PATCH /api/auth/me  — self-service profile update (role-aware)
// Updates User collection for all roles.
// Also syncs to Tutor doc (tutor role) or Student doc (student role).
router.patch('/me', protect, async (req, res) => {
  try {
    const { role, _id: userId, linkedId } = req.user;

    // ── 1. User collection ────────────────────────────────────────────────────
    const USER_FIELDS = [
      'firstName', 'lastName', 'displayName',
      'phone', 'dialCode', 'countryCode',
      'dob', 'gender', 'profileImage',
    ];
    const userUpdate = {};
    USER_FIELDS.forEach((f) => { if (req.body[f] !== undefined) userUpdate[f] = req.body[f]; });

    // Recompute `name` when first/last changes (findByIdAndUpdate skips pre-save hook)
    if (userUpdate.firstName !== undefined || userUpdate.lastName !== undefined) {
      const cur = await User.findById(userId).select('firstName lastName');
      const fn = userUpdate.firstName ?? cur.firstName;
      const ln = userUpdate.lastName  ?? (cur.lastName || '');
      userUpdate.name = [fn, ln].filter(Boolean).join(' ');
    }

    const updatedUser = await User.findByIdAndUpdate(
      userId, userUpdate, { new: true, runValidators: true },
    );
    if (!updatedUser) return res.status(404).json({ success: false, message: 'User not found' });

    // ── 2. Tutor doc sync ─────────────────────────────────────────────────────
    if (role === 'tutor' && linkedId) {
      const TUTOR_FIELDS = ['qualification', 'experience', 'subjects', 'phone', 'profileImage'];
      const tutorUpdate = {};
      TUTOR_FIELDS.forEach((f) => { if (req.body[f] !== undefined) tutorUpdate[f] = req.body[f]; });
      if (userUpdate.name) tutorUpdate.name = userUpdate.name;
      if (Object.keys(tutorUpdate).length > 0) {
        await Tutor.findByIdAndUpdate(linkedId, tutorUpdate);
      }
    }

    // ── 3. Student doc sync ───────────────────────────────────────────────────
    if (role === 'student' && linkedId) {
      const STUDENT_FIELDS = [
        'grade', 'subjects', 'parentName', 'parentEmail', 'parentPhone',
        'phone', 'profileImage',
      ];
      const studentUpdate = {};
      STUDENT_FIELDS.forEach((f) => { if (req.body[f] !== undefined) studentUpdate[f] = req.body[f]; });
      if (userUpdate.name) studentUpdate.name = userUpdate.name;
      if (Object.keys(studentUpdate).length > 0) {
        await Student.findByIdAndUpdate(linkedId, studentUpdate);
      }
    }

    res.json({ success: true, user: updatedUser.toJSON() });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
});

// PATCH /api/auth/me/change-password
router.patch('/me/change-password', protect, async (req, res) => {
  try {
    const { currentPassword, newPassword } = req.body;
    if (!currentPassword || !newPassword) {
      return res.status(400).json({ success: false, message: 'currentPassword and newPassword are required' });
    }
    if (newPassword.length < 6) {
      return res.status(400).json({ success: false, message: 'Password must be at least 6 characters' });
    }
    const user = await User.findById(req.user._id).select('+password');
    if (!user) return res.status(404).json({ success: false, message: 'User not found' });
    const ok = await user.comparePassword(currentPassword);
    if (!ok) return res.status(401).json({ success: false, message: 'Current password is incorrect' });
    user.password = newPassword;
    await user.save();
    res.json({ success: true, message: 'Password updated successfully' });
  } catch (err) {
    res.status(400).json({ success: false, message: err.message });
  }
});

router.post('/logout', protect, (req, res) => {
  res.json({ success: true, message: 'Logged out' });
});

module.exports = router;
