export interface Country {
  name: string;
  iso: string;     // ISO 3166-1 alpha-2
  dialCode: string;
  flag: string;    // emoji
}

const COUNTRIES: Country[] = [
  { name: 'Afghanistan', iso: 'AF', dialCode: '+93', flag: '🇦🇫' },
  { name: 'Albania', iso: 'AL', dialCode: '+355', flag: '🇦🇱' },
  { name: 'Algeria', iso: 'DZ', dialCode: '+213', flag: '🇩🇿' },
  { name: 'Argentina', iso: 'AR', dialCode: '+54', flag: '🇦🇷' },
  { name: 'Armenia', iso: 'AM', dialCode: '+374', flag: '🇦🇲' },
  { name: 'Australia', iso: 'AU', dialCode: '+61', flag: '🇦🇺' },
  { name: 'Austria', iso: 'AT', dialCode: '+43', flag: '🇦🇹' },
  { name: 'Azerbaijan', iso: 'AZ', dialCode: '+994', flag: '🇦🇿' },
  { name: 'Bahrain', iso: 'BH', dialCode: '+973', flag: '🇧🇭' },
  { name: 'Bangladesh', iso: 'BD', dialCode: '+880', flag: '🇧🇩' },
  { name: 'Belarus', iso: 'BY', dialCode: '+375', flag: '🇧🇾' },
  { name: 'Belgium', iso: 'BE', dialCode: '+32', flag: '🇧🇪' },
  { name: 'Bolivia', iso: 'BO', dialCode: '+591', flag: '🇧🇴' },
  { name: 'Bosnia and Herzegovina', iso: 'BA', dialCode: '+387', flag: '🇧🇦' },
  { name: 'Brazil', iso: 'BR', dialCode: '+55', flag: '🇧🇷' },
  { name: 'Bulgaria', iso: 'BG', dialCode: '+359', flag: '🇧🇬' },
  { name: 'Cambodia', iso: 'KH', dialCode: '+855', flag: '🇰🇭' },
  { name: 'Cameroon', iso: 'CM', dialCode: '+237', flag: '🇨🇲' },
  { name: 'Canada', iso: 'CA', dialCode: '+1', flag: '🇨🇦' },
  { name: 'Chile', iso: 'CL', dialCode: '+56', flag: '🇨🇱' },
  { name: 'China', iso: 'CN', dialCode: '+86', flag: '🇨🇳' },
  { name: 'Colombia', iso: 'CO', dialCode: '+57', flag: '🇨🇴' },
  { name: 'Croatia', iso: 'HR', dialCode: '+385', flag: '🇭🇷' },
  { name: 'Cyprus', iso: 'CY', dialCode: '+357', flag: '🇨🇾' },
  { name: 'Czech Republic', iso: 'CZ', dialCode: '+420', flag: '🇨🇿' },
  { name: 'Denmark', iso: 'DK', dialCode: '+45', flag: '🇩🇰' },
  { name: 'Ecuador', iso: 'EC', dialCode: '+593', flag: '🇪🇨' },
  { name: 'Egypt', iso: 'EG', dialCode: '+20', flag: '🇪🇬' },
  { name: 'Estonia', iso: 'EE', dialCode: '+372', flag: '🇪🇪' },
  { name: 'Ethiopia', iso: 'ET', dialCode: '+251', flag: '🇪🇹' },
  { name: 'Finland', iso: 'FI', dialCode: '+358', flag: '🇫🇮' },
  { name: 'France', iso: 'FR', dialCode: '+33', flag: '🇫🇷' },
  { name: 'Georgia', iso: 'GE', dialCode: '+995', flag: '🇬🇪' },
  { name: 'Germany', iso: 'DE', dialCode: '+49', flag: '🇩🇪' },
  { name: 'Ghana', iso: 'GH', dialCode: '+233', flag: '🇬🇭' },
  { name: 'Greece', iso: 'GR', dialCode: '+30', flag: '🇬🇷' },
  { name: 'Hong Kong', iso: 'HK', dialCode: '+852', flag: '🇭🇰' },
  { name: 'Hungary', iso: 'HU', dialCode: '+36', flag: '🇭🇺' },
  { name: 'Iceland', iso: 'IS', dialCode: '+354', flag: '🇮🇸' },
  { name: 'India', iso: 'IN', dialCode: '+91', flag: '🇮🇳' },
  { name: 'Indonesia', iso: 'ID', dialCode: '+62', flag: '🇮🇩' },
  { name: 'Iran', iso: 'IR', dialCode: '+98', flag: '🇮🇷' },
  { name: 'Iraq', iso: 'IQ', dialCode: '+964', flag: '🇮🇶' },
  { name: 'Ireland', iso: 'IE', dialCode: '+353', flag: '🇮🇪' },
  { name: 'Israel', iso: 'IL', dialCode: '+972', flag: '🇮🇱' },
  { name: 'Italy', iso: 'IT', dialCode: '+39', flag: '🇮🇹' },
  { name: 'Japan', iso: 'JP', dialCode: '+81', flag: '🇯🇵' },
  { name: 'Jordan', iso: 'JO', dialCode: '+962', flag: '🇯🇴' },
  { name: 'Kazakhstan', iso: 'KZ', dialCode: '+7', flag: '🇰🇿' },
  { name: 'Kenya', iso: 'KE', dialCode: '+254', flag: '🇰🇪' },
  { name: 'Kuwait', iso: 'KW', dialCode: '+965', flag: '🇰🇼' },
  { name: 'Kyrgyzstan', iso: 'KG', dialCode: '+996', flag: '🇰🇬' },
  { name: 'Latvia', iso: 'LV', dialCode: '+371', flag: '🇱🇻' },
  { name: 'Lebanon', iso: 'LB', dialCode: '+961', flag: '🇱🇧' },
  { name: 'Libya', iso: 'LY', dialCode: '+218', flag: '🇱🇾' },
  { name: 'Lithuania', iso: 'LT', dialCode: '+370', flag: '🇱🇹' },
  { name: 'Luxembourg', iso: 'LU', dialCode: '+352', flag: '🇱🇺' },
  { name: 'Malaysia', iso: 'MY', dialCode: '+60', flag: '🇲🇾' },
  { name: 'Maldives', iso: 'MV', dialCode: '+960', flag: '🇲🇻' },
  { name: 'Mexico', iso: 'MX', dialCode: '+52', flag: '🇲🇽' },
  { name: 'Moldova', iso: 'MD', dialCode: '+373', flag: '🇲🇩' },
  { name: 'Mongolia', iso: 'MN', dialCode: '+976', flag: '🇲🇳' },
  { name: 'Morocco', iso: 'MA', dialCode: '+212', flag: '🇲🇦' },
  { name: 'Myanmar', iso: 'MM', dialCode: '+95', flag: '🇲🇲' },
  { name: 'Nepal', iso: 'NP', dialCode: '+977', flag: '🇳🇵' },
  { name: 'Netherlands', iso: 'NL', dialCode: '+31', flag: '🇳🇱' },
  { name: 'New Zealand', iso: 'NZ', dialCode: '+64', flag: '🇳🇿' },
  { name: 'Nigeria', iso: 'NG', dialCode: '+234', flag: '🇳🇬' },
  { name: 'Norway', iso: 'NO', dialCode: '+47', flag: '🇳🇴' },
  { name: 'Oman', iso: 'OM', dialCode: '+968', flag: '🇴🇲' },
  { name: 'Pakistan', iso: 'PK', dialCode: '+92', flag: '🇵🇰' },
  { name: 'Palestine', iso: 'PS', dialCode: '+970', flag: '🇵🇸' },
  { name: 'Peru', iso: 'PE', dialCode: '+51', flag: '🇵🇪' },
  { name: 'Philippines', iso: 'PH', dialCode: '+63', flag: '🇵🇭' },
  { name: 'Poland', iso: 'PL', dialCode: '+48', flag: '🇵🇱' },
  { name: 'Portugal', iso: 'PT', dialCode: '+351', flag: '🇵🇹' },
  { name: 'Qatar', iso: 'QA', dialCode: '+974', flag: '🇶🇦' },
  { name: 'Romania', iso: 'RO', dialCode: '+40', flag: '🇷🇴' },
  { name: 'Russia', iso: 'RU', dialCode: '+7', flag: '🇷🇺' },
  { name: 'Saudi Arabia', iso: 'SA', dialCode: '+966', flag: '🇸🇦' },
  { name: 'Senegal', iso: 'SN', dialCode: '+221', flag: '🇸🇳' },
  { name: 'Serbia', iso: 'RS', dialCode: '+381', flag: '🇷🇸' },
  { name: 'Singapore', iso: 'SG', dialCode: '+65', flag: '🇸🇬' },
  { name: 'Slovakia', iso: 'SK', dialCode: '+421', flag: '🇸🇰' },
  { name: 'Slovenia', iso: 'SI', dialCode: '+386', flag: '🇸🇮' },
  { name: 'Somalia', iso: 'SO', dialCode: '+252', flag: '🇸🇴' },
  { name: 'South Africa', iso: 'ZA', dialCode: '+27', flag: '🇿🇦' },
  { name: 'South Korea', iso: 'KR', dialCode: '+82', flag: '🇰🇷' },
  { name: 'Spain', iso: 'ES', dialCode: '+34', flag: '🇪🇸' },
  { name: 'Sri Lanka', iso: 'LK', dialCode: '+94', flag: '🇱🇰' },
  { name: 'Sudan', iso: 'SD', dialCode: '+249', flag: '🇸🇩' },
  { name: 'Sweden', iso: 'SE', dialCode: '+46', flag: '🇸🇪' },
  { name: 'Switzerland', iso: 'CH', dialCode: '+41', flag: '🇨🇭' },
  { name: 'Syria', iso: 'SY', dialCode: '+963', flag: '🇸🇾' },
  { name: 'Taiwan', iso: 'TW', dialCode: '+886', flag: '🇹🇼' },
  { name: 'Tajikistan', iso: 'TJ', dialCode: '+992', flag: '🇹🇯' },
  { name: 'Tanzania', iso: 'TZ', dialCode: '+255', flag: '🇹🇿' },
  { name: 'Thailand', iso: 'TH', dialCode: '+66', flag: '🇹🇭' },
  { name: 'Tunisia', iso: 'TN', dialCode: '+216', flag: '🇹🇳' },
  { name: 'Turkey', iso: 'TR', dialCode: '+90', flag: '🇹🇷' },
  { name: 'Turkmenistan', iso: 'TM', dialCode: '+993', flag: '🇹🇲' },
  { name: 'Uganda', iso: 'UG', dialCode: '+256', flag: '🇺🇬' },
  { name: 'Ukraine', iso: 'UA', dialCode: '+380', flag: '🇺🇦' },
  { name: 'United Arab Emirates', iso: 'AE', dialCode: '+971', flag: '🇦🇪' },
  { name: 'United Kingdom', iso: 'GB', dialCode: '+44', flag: '🇬🇧' },
  { name: 'United States', iso: 'US', dialCode: '+1', flag: '🇺🇸' },
  { name: 'Uzbekistan', iso: 'UZ', dialCode: '+998', flag: '🇺🇿' },
  { name: 'Venezuela', iso: 'VE', dialCode: '+58', flag: '🇻🇪' },
  { name: 'Vietnam', iso: 'VN', dialCode: '+84', flag: '🇻🇳' },
  { name: 'Yemen', iso: 'YE', dialCode: '+967', flag: '🇾🇪' },
  { name: 'Zimbabwe', iso: 'ZW', dialCode: '+263', flag: '🇿🇼' },
];

export default COUNTRIES;

export function getCountryByIso(iso: string): Country | undefined {
  return COUNTRIES.find((c) => c.iso === iso);
}

export function searchCountries(query: string): Country[] {
  const q = query.toLowerCase();
  return COUNTRIES.filter(
    (c) => c.name.toLowerCase().includes(q) || c.dialCode.includes(q) || c.iso.toLowerCase().includes(q),
  );
}
